// 7.1 Aim of the program: Write a program to implement the matrix chain multiplication problem using M-table & S-table to find optimal 
// parenthesization of a matrix-chain product. Print the number of scalar multiplications required for the given input.
// Note# Dimensions of the matrices can be inputted as row and column values. Validate the dimension compatibility.
// Input: 
// Enter number of matrices: 4
// Enter row and col size of A1: 30  35
// Enter row and col size of A2: 35  15
// Enter row and col size of A3: 15  5
// Enter row and col size of A4: 5  10